#!/usr/bin/env node
/**
 * Generate a local --patch overlay for the built Host, Client, and preset.
 * The paths must be absolute because dsh resolves overlay module names from
 * the profile directory, not from the overlay file's directory.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const host = resolve(root, "lib/index.js");
const client = resolve(root, "lib/client.js");
const preset = resolve(root, "digital-life-mode.patch.yml");
for (const entry of [host, client]) {
  if (!existsSync(entry)) {
    console.error(`missing ${entry}; run \`pnpm run build\` first`);
    process.exit(1);
  }
}

const output = resolve(root, "dev/cordis.dev.local.yml");
mkdirSync(resolve(root, "dev"), { recursive: true });
writeFileSync(
  output,
  [
    "# Generated by scripts/dev-patch.mjs; do not edit.",
    "- insert:",
    "    - id: dev-digital-life-host",
    `      name: '${host}'`,
    "    - id: dev-digital-life-client",
    `      name: '${client}'`,
    "",
  ].join("\n") + readFileSync(preset, "utf8"),
);
console.log(`wrote ${output}`);
